/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC165Contract } from "./ERC165";
import { ERC20Contract } from "./ERC20";
import { ERC721Contract } from "./ERC721";
import { ERC721EnumerableContract } from "./ERC721Enumerable";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { INFTKEYMarketplaceRoyaltyContract } from "./INFTKEYMarketplaceRoyalty";
import { INFTKEYMarketplaceV2Contract } from "./INFTKEYMarketplaceV2";
import { MigrationsContract } from "./Migrations";
import { NFTKEYMarketplaceRoyaltyContract } from "./NFTKEYMarketplaceRoyalty";
import { NFTKEYMarketplaceV2Contract } from "./NFTKEYMarketplaceV2";
import { OwnableContract } from "./Ownable";
import { TestERC20Contract } from "./TestERC20";
import { TestERC721Contract } from "./TestERC721";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721Enumerable"): ERC721EnumerableContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(
        name: "INFTKEYMarketplaceRoyalty"
      ): INFTKEYMarketplaceRoyaltyContract;
      require(name: "INFTKEYMarketplaceV2"): INFTKEYMarketplaceV2Contract;
      require(name: "Migrations"): MigrationsContract;
      require(
        name: "NFTKEYMarketplaceRoyalty"
      ): NFTKEYMarketplaceRoyaltyContract;
      require(name: "NFTKEYMarketplaceV2"): NFTKEYMarketplaceV2Contract;
      require(name: "Ownable"): OwnableContract;
      require(name: "TestERC20"): TestERC20Contract;
      require(name: "TestERC721"): TestERC721Contract;
    }
  }
}

export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721EnumerableContract,
  ERC721EnumerableInstance,
} from "./ERC721Enumerable";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export {
  INFTKEYMarketplaceRoyaltyContract,
  INFTKEYMarketplaceRoyaltyInstance,
} from "./INFTKEYMarketplaceRoyalty";
export {
  INFTKEYMarketplaceV2Contract,
  INFTKEYMarketplaceV2Instance,
} from "./INFTKEYMarketplaceV2";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  NFTKEYMarketplaceRoyaltyContract,
  NFTKEYMarketplaceRoyaltyInstance,
} from "./NFTKEYMarketplaceRoyalty";
export {
  NFTKEYMarketplaceV2Contract,
  NFTKEYMarketplaceV2Instance,
} from "./NFTKEYMarketplaceV2";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { TestERC20Contract, TestERC20Instance } from "./TestERC20";
export { TestERC721Contract, TestERC721Instance } from "./TestERC721";
